### ISSUE TITLE
Proposal: Add code annotation gems by default

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#366]
I have found these code annotation gems to be extremely useful on projects. Should they be added by default?

```ruby
group :development do
  gem "chusaku", require: false
  gem "annotate", require: false
end
```

I configure `annotate` to run automatically via `rails g annotate:install` and I add the following CI checks to make sure they both are up to date:

```yml
      - name: Check Run Ruby model annotations
        run: bundle exec annotate --frozen
      - name: Check Ruby controller annotations
        run: bundle exec chusaku --exit-with-error-on-annotation
```

I have found the overhead of keeping these annotations up to date to be minimal and having the annotations extremely useful, especially on larger apps.
