### ISSUE TITLE
Set sensible box-sizing CSS in all generated apps

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#480]
All of our projects (as far as I am aware) set a sensible `box-sizing` - something like:

```scss
// Use sane box-sizing
// https://css-tricks.com/box-sizing/#aa-universal-box-sizing-with-inheritance
html {
  box-sizing: border-box;
}

*,
*::before,
*::after {
  box-sizing: inherit;
}
```

I think the SCSS generated by this template should do this because it is very annoying to fix this if a team has already built a bunch of CSS
