### ISSUE TITLE
Turn up webpacker verbosity in production environment

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/rails-template#8]
The Rails 6 default is to supress webpacker output during compilation [1]. This leads to very obscure build failures that end with "...Compilation failed", with no reason why.

We should probably apply the `webpack_compile_output: true` setting for production & staging environments to make sure that if asset compilation fails, we understand why. 

Here's a patch:

```
commit b4698d7b0641d538a0cabb538a38178a9b093a56 (HEAD -> bugfix/resolve-deployment-failures)
Author: Josh McArthur <joshua.mcarthur@gmail.com>
Date:   Tue Sep 24 14:12:09 2019 +1200

    Enable webpacker compilation output when compiling in deployed environments

diff --git a/config/webpacker.yml b/config/webpacker.yml
index 88332c5..2046dc9 100644
--- a/config/webpacker.yml
+++ b/config/webpacker.yml
@@ -94,3 +94,6 @@ production:

   # Cache manifest.json for performance
   cache_manifest: true
+
+  # Provide output for deployment precompilation
+  webpack_compile_output: true

```

**Comment by eoinkelly** [comment]
I think Rails 6.0.1 might be doing what we want out of the box. It sets ` webpack_compile_output: true` in the default block  and doesn't unset it anywhere. 

I get the file below when I create a new app with this template:

```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/frontend
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```
